# Meta Data for SEO

## Homepage
title = "AzureCP"
titleSeparator = "-"
titleAddition = "Claims provider for Azure AD authentication in SharePoint Subscription / 2019 / 2016 / 2013"
description = "AzureCP connects SharePoint Subscription / 2019 / 2016 / 2013 with Azure Active Directory to fix the search in the people picker in Azure AD authentication"

## Documentation
# docsVersion = "0.3"

## Open Graph
#images = ["doks.png"]
ogLocale = "en_US"
domainTLD = "azurecp.yvand.net"
titleHome = "AzureCP"

## Twitter Cards
#twitterSite = "yvand"
#twitterCreator = "yvand"

## JSON-LD
schemaType = "Organization"
schemaName = "AzureCP"
schemaAuthor = "Yvan Duhamel"
schemaAuthorTwitter = "https://twitter.com/yvand"
schemaAuthorLinkedIn = "https://www.linkedin.com/in/yvand/"
schemaAuthorGitHub = "https://github.com/Yvand"
schemaLocale = "en-US"
schemaLogo = "logo-doks.png"
schemaLogoWidth = 512
schemaLogoHeight = 512
schemaImage = "doks.png"
schemaImageWidth = 1280
schemaImageHeight = 640
schemaTwitter = "https://twitter.com/yvand"
schemaLinkedIn = ""
schemaGitHub = "https://github.com/Yvand/AzureCP"
schemaSection = "blog"

## Sitelinks Search Box
siteLinksSearchBox = false

## Chrome Browser
themeColor = "#fff"

# Images
quality = 85
bgColor = "#fff"
landscapePhotoWidths = [900, 800, 700, 600, 500]
portraitPhotoWidths = [800, 700, 600, 500]
lqipWidth = "20x"
smallLimit = "300"

# Footer
footer = "Site built with <a href=\"https://gohugo.io/\" class=\"gdoc-footer__link\" target=\"_blank\">Hugo</a> and <a class=\"gdoc-footer__link\" href=\"https://getdoks.org/\" target=\"_blank\">Doks</a>. Project developed and maintained with ❤️ by <a href=\"https://www.linkedin.com/in/yvand/\" class=\"gdoc-footer__link\" target=\"_blank\">Yvan Duhamel</a>."

# Feed
copyRight = "Copyright (c) 2020-2022 Yvan Duhamel"

# Alert
alert = false
alertDismissable = true
alertText = "Like AzureCP? <a class=\"alert-link\" href=\"https://github.com/Yvand/AzureCP/stargazers\">Star on GitHub</a>. Thanks!</a>"

# Edit Page
# repoHost [Github | Gitea | GitLab | Bitbucket | BitbucketServer ] is used for building the edit link based on git hoster
repoHost = "GitHub"
docsRepo = "https://github.com/Yvand/hugo-AzureCP"
docsRepoBranch = "main"
docsRepoSubPath = ""
editPage = false
lastMod = true

[options]
  lazySizes = true
  clipBoard = true
  instantPage = true
  flexSearch = true
  searchSectionsShow = []
  searchSectionsIndex = []
  darkMode = true
  bootStrapJs = true
  breadCrumb = false
  highLight = true
  kaTex = false
  multilingualMode = false
  docsVersioning = false
  fullWidth = true

[menu]
  [menu.section]
    auto = false
    collapsibleSidebar = false
